# name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: '.'
        target: '~/konnect-backend'  # 다시 konnect-backend 디렉토리로 변경
        overwrite: true
    
    - name: Restart Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/konnect-backend  # konnect-backend 디렉토리 생성
          cd ~/konnect-backend
          npm install
          pm2 delete app || true
          pm2 start npm --name "app" -- start
