name: Deploy to EC2

on:
  push:
    branches: [ main ]  # 필요에 따라 브랜치명 변경

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build Application (로컬 빌드)
      run: npm run build
    
    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        # 모든 필요한 파일과 디렉토리 포함
        source: "dist/,node_modules/,src/,package.json,package-lock.json,ecosystem.config.js,.env,dataSource.ts,tsconfig.json,nest-cli.json"
        target: "~/konnect-backend"
        strip_components: 0
        # 기존 파일 덮어쓰기
        overwrite: true
    
    - name: Deploy and Restart Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/konnect-backend
          
          # 환경 설정
          export PATH=$PATH:$HOME/.npm-global/bin
          
          # 애플리케이션 다시 빌드
          npm run build
          
          # PM2 경로 설정
          PM2_PATH="/home/ubuntu/.npm-global/bin/pm2"
          
          # PM2로 애플리케이션 재시작
          if $PM2_PATH list | grep -q "konnect"; then
            echo "Reloading existing PM2 process"
            $PM2_PATH reload konnect || $PM2_PATH reload ecosystem.config.js
          else
            echo "Starting new PM2 process"
            $PM2_PATH start ecosystem.config.js
          fi
          
          # 배포 완료 메시지
          echo "Deployment completed successfully"
