name: Deploy to EC2

# main 브랜치에 push할 때 실행한당
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # 의존성 설치
      - name: Install dependencies
        run: |
          cd backend
          npm ci

      # 프로젝트 빌드
      - name: Build
        run: |
          cd backend
          npm run build

      # 배포 패키지 생성
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r dist package.json package-lock.json .env.example deployment/
          cd deployment && zip -r ../deployment.zip .

      # EC2로 파일 전송
      - name: Upload to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deployment.zip"
          target: "~/deployment"

      # EC2에서 배포 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/deployment/temp
            cd ~/deployment
            unzip -o deployment.zip -d temp
            cp -a temp/. ~/konnent/backend/
            cd ~/konnent/backend
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm ci --production
            pm2 restart konnect-backend
